### ISSUE TITLE
How to save a file uploaded as a stream in mongodb

### ISSUE THREAD

**Issue by shaheenmasood** [ashaffer/mongoose-write-stream#1]
Hi ashaffer,

I am planning to use mongoose-write-stream to save a file in a mongoDB collection as binary data uploaded as a stream using 'busboy'. The example I see streams all the columns of a document. But, in my collection :

var BinfsSchema = new Schema({
    filename: String,
    contentType: String,
    length: Number,
    uploadDate: { type: Date, default: Date.now }, 
    bin: Buffer,
    metadata: {}
}, { collection : 'files' });

Only the 'bin' column contains binary data that I can get from readstream and rest of the columns contain static data. How can I handle this?

Your example

readstream.pipe(Tick.writeStream()) populates all the columns in a collection, how to I populate only one column?

Thanks,

-- shaheen

**Comment by ashaffer** [comment]
Sorry for the extremely delayed response.  I'm not sure what you're asking exactly.  Are you saying that you are trying to save a single document, which has several static fields and one field that you'd like to write in as a stream?

If so, that's not what this plugin is designed to do exactly.  There's probably a way to do what you're asking but i'm not sure how to do it.

Or am I misinterpreting your question?

**Comment by shaheenmasood** [comment]
You are correct about my question. I figured out how to do it without using
the plugin. Thanks for the response.

**Comment by nitthilan** [comment]
Hi Shaheenmasood,
    Is it possible to explain or share how you did this without the plugin. I too wanted to do something similar.

Regards,
K. J. N

**Comment by rbecheras** [comment]
Hi @shaheenmasood ! 

As @nitthilan , I really would want to know how you did it. 

I wanna do it to day I had to write temp file instead of mongo buffer for now... 

I still search how to do it.
